global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
api:
  insecure: true
  dashboard: true
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
